
TRANSLATIONS = {
    "ja": {
        "app_title": "鳴潮 音骸スコア計算機",
        "char_setting_title": "キャラクター設定",
        "char_name": "キャラクター名:",
        "char_name_en": "英語名:",
        "char_name_en_placeholder": "英語名を入力 (例: Calcharo)",
        "cost_config": "コスト構成:",
        "echo_5_slot_config": "エコー5枠構成",
        "cost_echo": "コスト{}エコー",
        "effective_substats_weights": "有効サブステータスと重み係数入力欄（5個）",
        "effective_substat_n": "有効サブステータス{}",
        "weight": "重み:",
        "save": "保存",
        "close": "閉じる",
        "error": "エラー",
        "enter_char_name": "キャラクター名を入力してください",
        "enter_char_name_en": "英語名を入力してください",
        "base_stat_offsets": "基礎ステータス・武器補正 (Base/Weapon Offsets)",
        "scaling_stat_label": "参照ステータス:",
        "base_stat_label": "基礎値 (本体+武器):",
        "ideal_stat_label": "理想値 (目標ステ):",
        "crit_offset": "クリ補正:",
        "crit_offset_tooltip": "武器や基礎ステータスによるクリティカル率の合計値を入力。CV計算の目標達成度判定に使用します。",
        "echo_main_stat_unselected": "エコー{}メインステータス未選択",
        "save_complete": "保存完了",
        "save_msg": "{}の設定を保存しました",
        "basic_settings": "基本設定",
        "character": "キャラ:",
        "input_mode": "入力:",
        "manual": "手動",
        "ocr": "OCR",
        "auto_main": "メイン自動",
        "auto_calculate": "自動計算",
        "calc_mode": "計算:",
        "methods_label": "評価方式:",
        "batch": "一括",
        "single_only": "選択のみ",
        "calculate": "計算",
        "export_txt": "TXT出力",
        "clear_all": "全クリア",
        "clear_tab": "タブクリア",
        "char_setting": "キャラ設定",
        "help": "ヘルプ",
        "ocr_image": "OCR画像",
        "load_image": "画像読込",
        "paste_clipboard": "クリップボードから貼付 (Ctrl+V)",
        "perform_crop": "切り取り実行",
        "crop_mode": "切り取りモード:",
        "drag": "ドラッグ",
        "percent": "％指定",
        "top_percent": "上%:",
        "right_percent": "右%:",
        "no_image": "No Image",
        "calc_result": "計算結果",
        "log": "ログ",
        "main_stat": "メイン",
        "substats": "サブステータス",
        "ratio": "倍率: {}",
        "tab_clear_success": "タブ '{}' をクリアしました",
        "export_success": "エクスポート成功",
        "export_msg": "結果をTXTファイルにエクスポートしました。",
        "ocr_library_missing": "OCRモードには以下のライブラリが必要です:\n{}\n\n手動モードに戻します。",
        "ocr_auto_fill_fail_no_tab": "OCR自動入力失敗: タブが選択されていません",
        "ocr_auto_fill_fail_tab_not_found": "OCR自動入力失敗: タブ'{}'が見つかりません",
        "ocr_auto_fill_success": "OCR自動入力: サブ{} → {} {}{}",
        "clipboard_no_image": "クリップボードに画像がありません",
        "clipboard_error": "クリップボード読み込みエラー: {}",
        "image_not_loaded": "画像が読み込まれていません",
        "file_not_found": "ファイルが見つかりません:\n{}",
        "image_select_cancelled": "画像選択をキャンセルしました",
        "select_image_file": "画像ファイルを選択",
        "image_files": "画像ファイル",
        "all_files": "すべてのファイル",
        "pillow_required": "OCRモードを利用するにはPillowが必要です。",
        "crop_cancel": "クロップキャンセル",
        "image_loaded": "画像を読み込みました: {}",
        "ocr_success": "OCR成功 (文字数: {})",
        "ocr_no_text": "OCR結果: テキスト未検出",
        "ocr_tesseract_not_found": "Tesseract実行ファイルが見つかりません (設定: {})",
        "ocr_lang_data_error": "OCR言語データ(jpn)が見つかりません。\nTesseractの日本語辞書(jpn.traineddata)をインストールしてください。\n詳細: {}",
        "ocr_process_error": "OCR処理でエラーが発生しました:\n{}",
        "data_save_success": "データを保存しました",
        "data_load_success": "データ読込完了（必要な項目を反映）",
        "data_load_error": "読込失敗: {}",
        "waiting_for_character": "キャラクターを選択してください。選択後に計算を実行します。",
        "log_waiting_for_character": "キャラクター未選択のため、計算を待機しています。",
        "settings_loaded": "設定を読み込みました",
        "language": "言語 (Language):",
        "restart_required": "再起動が必要です",
        "restart_msg": "言語設定を変更しました。適用するにはアプリケーションを再起動してください。",
        "language_changed_title": "言語変更",
        "language_changed_message": "言語設定を切り替えました。",
        "score_calc_error": "スコア計算エラー: {}",
        "tab_not_selected": "タブが選択されていません",
        "tab_info_error": "タブ情報取得エラー",
        "main_stat_missing": "{}: メインステータスが未入力です",
        "individual_score_title": "【{}】個別スコア計算 - {}\n",
        "echo_info": "【音骸情報】\n",
        "level": "レベル: {}\n",
        "effective_substat_count": "有効サブステ数: {}/5\n\n",
        "substat_header": "【サブステータス】\n",
        "none": "  （なし）\n",
        "score_by_method": "【評価方式別スコア】\n\n",
        "score_label": "   スコア",
        "rating_label": "   評価",
        "desc_label": "   説明",
        "overall_eval": "【総合評価】\n",
        "estimated_total_stats": "【推定トータルステータス】\n",
        "total_score": "総合スコア",
        "overall_rating": "総合評価",
        "recommendation": "推奨度",
        "batch_score_title": "【{}】音骸セット総合評価\n",
        "calculated_count": "計算済み音骸数: {}/{}\n",
        "echo_n_header": "\n【音骸 {}】{}\n",
        "set_total_score": "【セット全体の合計スコア】\n",
        "set_avg_score": "【セット全体の平均スコア】\n",
        "final_evaluation": "【最終評価】\n",
        "achievement_rate_label": "厳選達成率",
        "achievement_rate_desc": "理想のサブステ5種がMaxロールだった場合を100%とした達成度",
        "sss_desc": "SSS級 - 完璧な音骸セット！理論値級の性能です",
        "ss_desc": "SS級 - 非常に優秀なセット。ほぼ完成形です",
        "s_desc": "S級 - 優秀なセット。実戦で十分な性能です",
        "a_desc": "A級 - 良好なセット。使用に問題ありません",
        "b_desc": "B級 - 及第点。改善の余地があります",
        "c_desc": "C級 - 要改善。厳選を継続することをお勧めします",
        "normalized_score_desc": "各サブステを最大値で正規化し重み付け",
        "ratio_score_desc": "サブステ比率とダメージ上昇を考慮",
        "roll_quality_desc": "各サブステの引き強度を個別評価",
        "effective_stat_desc": "有効なサブステ数にボーナス付与",
        "normalized_score_label": "正規化スコア方式 (GameWith式)",
        "ratio_score_label": "比率重視方式 (Keisan式)",
        "roll_quality_label": "ロール品質方式",
        "effective_stat_label": "有効ステータス数方式",
        "cost_label": "コスト: {}",
        "score_point": "{:.2f}点",
        "score_per_item": "{:.2f}点/個",
        "score_point_count": "{:.2f}点 [{}個]",
        "total_score_label": "総合スコア",
        "total_label": "総合",
        "normalized_label": "正規化",
        "ratio_label": "比率",
        "roll_label": "ロール",
        "effective_label": "有効ステ",
        "effective_count_label": "有効数",
        "recommend_label": "推奨",
        "warning": "警告",
        "no_data": "計算可能な音骸データがありません",
        "individual_eval_done": "個別詳細評価完了: {} - 総合{:.2f}点",
        "batch_eval_done": "まとめて詳細評価完了: {}個計算",
        "calc_error": "計算エラー:\n{}",
        "batch_calc_error": "まとめて評価エラー: {}",
        "batch_error_msg": "まとめて計算でエラーが発生しました:\n{}",
        "image_load_error": "画像の読み込みに失敗しました:\n{}",
        "image_load_error_log": "画像読み込みエラー: {}",
        "pytesseract_not_installed": "pytesseractがインストールされていないためOCRを実行できません",
        "tesseract_found_path": "TesseractがPATHから発見されました: {}",
        "tesseract_not_found_sys": "Tesseractが見つかりません。パスを設定するか、システムにインストールしてください。",
        "ocr_error_title": "OCRエラー",
        "ocr_lang_data_error_log": "OCR言語データエラー: {}",
        "tesseract_exec_not_found": "Tesseract実行ファイルが見つかりません:\n{}",
        "tesseract_exec_error_log": "Tesseract実行ファイルエラー: {}",
        "ocr_process_error_log": "OCR処理エラー: {}",
        "crop_title": "画像切り取り",
        "crop_instruction": "マウスドラッグで切り取り範囲を指定してください。",
        "crop_sync_notice": "※ここで保存した位置(L,T)とサイズ(W,H)は、メイン画面のスライダー(％指定)と同期され、自動計算時に使用されます。",
        "crop_confirm_apply": "適用確認",
        "crop_apply_percent": "%設定エリアを適用",
        "crop_apply_percent_tooltip": "選択した領域の幅/高さをパーセントとして扱い、元画像に対して割合で切り取ります。例: 50% x 50%",
        "crop_save_as_default": "設定をメイン画面のスライダーと同期して保存",
        "crop_save_as_default_tooltip": "この範囲(L,T,W,H)をメイン画面の％指定スライダーに即座に反映し、次回以降のデフォルト値（自動計算時の範囲）として保存します。",
        "crop_confirm_needed": "適用するにはチェックボックスをオンにしてください",
        "preset_name_placeholder": "名前",
        "preset_placeholder_format": "L,T,W,H (%)",
        "preset_name_required": "プリセット名を入力してください",
        "preset_format": "プリセット形式が正しくありません (例: 50x50)",
        "ok": "決定",
        "cancel": "キャンセル",
        "reset": "リセット",
        "save": "保存",
        "load": "読込",
        "delete": "削除",
        "info": "情報",
        "crop_too_small": "選択範囲が小さすぎます",
        "text_color": "テキスト色:",
        "select_color": "色選択",
        "apply": "適用",
        "background_image": "背景画像:",
        "select_image": "画像を選択",
        "clear_image": "クリア",
        "bg_opacity": "背景不透明度:",
        "help_customization": "見た目のカスタマイズ ヘルプ",
        "font_settings": "フォント設定",
        "font_family": "フォント:",
        "default_font": "システムデフォルト",
        "weight_template": "重みテンプレート:",
        "custom": "カスタム",
        "title_warning": "警告",
        "warn_legacy_bg_not_found": "以前設定された背景画像が次の場所に見つかりませんでした:\n\n{0}\n\n設定はクリアされました。",
        # Stats
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "攻撃力",
        "攻撃力%": "攻撃力%",
        "防御力": "防御力",
        "防御力%": "防御力%",
        "クリティカル率": "クリティカル率",
        "クリティカルダメージ": "クリティカルダメージ",
        "共鳴効率": "共鳴効率",
        "通常攻撃ダメージアップ": "通常攻撃ダメージアップ",
        "重撃ダメージアップ": "重撃ダメージアップ",
        "共鳴スキルダメージアップ": "共鳴スキルダメージアップ",
        "共鳴解放ダメージアップ": "共鳴解放ダメージアップ",
        "焦熱ダメージアップ": "焦熱ダメージアップ",
        "凝縮ダメージアップ": "凝縮ダメージアップ",
        "電導ダメージアップ": "電導ダメージアップ",
        "気動ダメージアップ": "気動ダメージアップ",
        "回折ダメージアップ": "回折ダメージアップ",
        "消滅ダメージアップ": "消滅ダメージアップ",
        "HP回復効果アップ": "HP回復効果アップ",
        # Ratings
        "rating_sss_norm": "SS級 - 最高品質",
        "rating_ss_norm": "S級 - 優秀",
        "rating_s_norm": "A級 - 実用的",
        "rating_b_norm": "B級 - 要改善",
        "rating_perf_ratio": "完璧 - 理論値に近い",
        "rating_exc_ratio": "優秀 - 十分強い",
        "rating_good_ratio": "良好 - 使用可能",
        "rating_avg_ratio": "普通 - 改善推奨",
        "rating_weak_ratio": "弱い - 厳選必要",
        "rating_god_roll": "神引き - 最高ロール連続",
        "rating_win_roll": "当たり - 高品質ロール多数",
        "rating_avg_roll": "平均的 - 標準的ロール",
        "rating_bad_roll": "ハズレ - 低品質ロール",
        "rating_perf_eff": "完璧 - 5有効ステ ({:.1f}点)",
        "rating_exc_eff": "優秀 - 4有効ステ ({:.1f}点)",
        "rating_good_eff": "良好 - 3有効ステ ({:.1f}点)",
        "rating_bad_eff": "要改善 - {}有効ステ ({:.1f}点)",
        "rating_sss_global": "SSS - 完璧な音骸セット!",
        "rating_ss_global": "SS - 非常に優秀",
        "rating_s_global": "S - 優秀",
        "rating_a_global": "A - 良好",
        "rating_b_global": "B - 合格",
        "rating_c_global": "C - 要改善",
        "rec_continue": "厳選継続",
        "rec_use": "使用推奨",
        "theme": "ライト/ダーク",
        "display_settings": "表示設定",
        # Character Names
        "CarlottaNew": "カルロッタNew",
        "Cantarella": "カンタレラ",
        "Tsubaki": "ツバキ",
        "Changli": "長離",
        "General": "汎用",
        "rating_sss_single": "SSS - 完璧な音骸! 理想的な性能です",
        "rating_ss_single": "SS - 非常に優秀な音骸",
        "rating_s_single": "S - 優秀な音骸",
        "rating_a_single": "A - 良好な音骸",
        "rating_b_single": "B - 使用可能",
        "rating_c_single": "C - 厳選推奨",
        # CV Method Ratings
        "rating_outstanding_cv": "最高級 - 45点以上 (SSS級)",
        "rating_excellent_cv": "非常に優秀 - 38~45点 (S級)",
        "rating_good_cv": "優秀 - 30~38点 (目標達成)",
        "rating_acceptable_cv": "合格 - 25~30点 (最低ライン)",
        "rating_weak_cv": "要厳選 - 25点未満",
        # Method Labels
        "cv_score_label": "CV換算方式 (コミュニティ標準)",
        "cv_score_desc": "会心値を基準とした評価（30点合格/38点目標）",
        # Method Selection
        "calc_methods": "計算方式:",
        "method_normalized": "正規化",
        "method_ratio": "比率重視",
        "method_roll": "ロール品質",
        "method_effective": "有効ステ数",
        "method_cv": "CV換算",
        "no_methods_selected": "少なくとも1つの計算方式を選択してください",
        "cleanup_title": "背景画像のクリーンアップ",
        "cleanup_button": "クリーンアップ",
        "cleanup_no_folder": "imagesフォルダが見つかりません。",
        "cleanup_no_unused": "未使用の背景画像はありません。",
        "cleanup_confirm": "{}個の未使用画像を削除しますか？\n\n{}",
        "cleanup_error": "{}個の画像を削除しましたが、以下のファイルの削除中にエラーが発生しました:\n\n{}",
        "cleanup_success": "{}個の未使用画像を削除しました。",
        "cleanup_unexpected_error": "クリーンアップ中に予期せぬエラーが発生しました:\n{}",
        "new": "新規作成",
        "edit": "編集",
        "char_setting_new": "キャラクター設定(新規)",
        "char_setting_edit": "キャラクター設定(編集)",
        "history_title": "計算履歴",
        "history": "履歴",
        "preprocess_settings": "前処理設定",
        "history_search": "検索:",
        "history_char": "キャラ:",
        "history_cost": "コスト:",
        "history_rating": "評価:",
        "history_from": "開始日:",
        "history_to": "終了日:",
        "history_filter_date": "日付で絞り込む",
        "history_reset": "リセット",
        "history_clear": "履歴を全削除",
        "history_stats": "件数: {} | 平均スコア: {:.2f} | 最高スコア: {:.2f}",
        "history_no_data": "現在の条件に一致するスコアデータはありません。",
        "history_col_time": "日時",
        "history_col_char": "キャラクター",
        "history_col_cost": "コスト",
        "history_col_action": "アクション",
        "history_col_result": "結果",
        "history_duplicate_mode": "重複履歴の挙動:",
        "history_dup_all": "すべて保存 (重複を許可)",
        "history_dup_latest": "最新を保持 (古い履歴を削除)",
        "history_dup_oldest": "最古を保持 (新しい履歴を無視)",
        "history_duplicate_tooltip": "同じステータスの音骸を計算した際の挙動を設定します。\n・すべて保存: 重複を気にせず追加します。\n・最新を保持: 古い履歴を消して、今回計算した時刻で上書きします。\n・最古を保持: 既に履歴にある場合は追加せず、最初に手に入れた（計算した）時刻を維持します。",
    },
    "en": {
        "app_title": "Wuthering Waves Echo Score Calculator",
        "char_setting_title": "Character Settings",
        "char_name": "Character Name:",
        "char_name_en": "English Name:",
        "char_name_en_placeholder": "Enter English name (e.g., Calcharo)",
        "cost_config": "Cost Config:",
        "echo_5_slot_config": "Echo 5-Slot Configuration",
        "cost_echo": "Cost {} Echo",
        "effective_substats_weights": "Effective Substats & Weights (5 slots)",
        "effective_substat_n": "Effective Substat {}",
        "weight": "Weight:",
        "save": "Save",
        "close": "Close",
        "error": "Error",
        "enter_char_name": "Please enter a character name",
        "enter_char_name_en": "Please enter an English name",
        "base_stat_offsets": "Character/Weapon Stat Offsets",
        "scaling_stat_label": "Scaling Stat:",
        "base_stat_label": "Base (Char+Weapon):",
        "ideal_stat_label": "Ideal (Target Stat):",
        "crit_offset": "Crit Offset:",
        "crit_offset_tooltip": "Enter total crit rate from weapon and base stats. Used for CV rating calculation.",
        "echo_main_stat_unselected": "Echo {} Main Stat not selected",
        "save_complete": "Save Complete",
        "save_msg": "Settings for {} saved",
        "basic_settings": "Basic Settings",
        "character": "Char:",
        "input_mode": "Input:",
        "manual": "Manual",
        "ocr": "OCR",
        "auto_main": "Auto Main",
        "auto_calculate": "Auto Calc",
        "calc_mode": "Calc:",
        "methods_label": "Methods:",
        "batch": "Batch",
        "single_only": "Single",
        "calculate": "Calculate",
        "export_txt": "Export TXT",
        "clear_all": "Clear All",
        "clear_tab": "Clear Tab",
        "char_setting": "Char Set",
        "help": "Help",
        "ocr_image": "OCR Image",
        "load_image": "Load Image",
        "paste_clipboard": "Paste Clipboard (Ctrl+V)",
        "perform_crop": "Crop",
        "crop_mode": "Crop Mode:",
        "drag": "Drag",
        "percent": "Percent",
        "top_percent": "Top%:",
        "right_percent": "Right%:",
        "no_image": "No Image",
        "calc_result": "Results",
        "log": "Log",
        "main_stat": "Main",
        "substats": "Substats",
        "ratio": "Ratio: {}",
        "tab_clear_success": "Cleared tab '{}'",
        "export_success": "Export Success",
        "export_msg": "Result exported to TXT file.",
        "ocr_library_missing": "OCR mode requires the following libraries:\n{}\n\nReverting to Manual mode.",
        "ocr_auto_fill_fail_no_tab": "OCR Auto-fill Failed: No tab selected",
        "ocr_auto_fill_fail_tab_not_found": "OCR Auto-fill Failed: Tab '{}' not found",
        "ocr_auto_fill_success": "OCR Auto-fill: Sub{} -> {} {}{}",
        "clipboard_no_image": "No image in clipboard",
        "clipboard_error": "Clipboard load error: {}",
        "image_not_loaded": "Image not loaded",
        "file_not_found": "File not found:\n{}",
        "image_select_cancelled": "Image selection cancelled",
        "select_image_file": "Select Image File",
        "image_files": "Image Files",
        "all_files": "All Files",
        "pillow_required": "Pillow is required for OCR mode.",
        "crop_cancel": "Crop cancelled",
        "image_loaded": "Image loaded: {}",
        "ocr_success": "OCR Success (Chars: {})",
        "ocr_no_text": "OCR Result: No text detected",
        "ocr_tesseract_not_found": "Tesseract executable not found (Config: {})",
        "ocr_lang_data_error": "OCR language data (jpn) not found.\nPlease install Tesseract Japanese data (jpn.traineddata).\nDetail: {}",
        "ocr_process_error": "OCR Process Error:\n{}",
        "data_save_success": "Data saved",
        "data_load_success": "Data loaded (Applied necessary items)",
        "data_load_error": "Load Failed: {}",
        "waiting_for_character": "Please select a character. Calculation will run after selection.",
        "log_waiting_for_character": "Calculation is waiting for character selection.",
        "settings_loaded": "Settings loaded",
        "language": "Language:",
        "restart_required": "Restart Required",
        "restart_msg": "Language setting changed. Please restart the application to apply.",
        "language_changed_title": "Language Changed",
        "language_changed_message": "Language setting has been switched.",
        "score_calc_error": "Score Calc Error: {}",
        "tab_not_selected": "Tab not selected",
        "tab_info_error": "Tab info error",
        "main_stat_missing": "{}: Main stat missing",
        "individual_score_title": "[{}] Individual Score - {}\n",
        "echo_info": "[Echo Info]\n",
        "level": "Level: {}\n",
        "effective_substat_count": "Effective Substats: {}/5\n\n",
        "substat_header": "[Substats]\n",
        "none": "  (None)\n",
        "score_by_method": "[Score by Method]\n\n",
        "score_label": "   Score",
        "rating_label": "   Rating",
        "desc_label": "   Desc",
        "overall_eval": "[Overall Evaluation]\n",
        "estimated_total_stats": "[Estimated Total Stats]\n",
        "total_score": "Total Score",
        "overall_rating": "Overall Rating",
        "recommendation": "Recommendation",
        "batch_score_title": "[{}] Echo Set Total Evaluation\n",
        "calculated_count": "Calculated Echoes: {}/{}\n",
        "echo_n_header": "\n[Echo {}] {}\n",
        "set_total_score": "[Set Total Score]\n",
        "set_avg_score": "[Set Average Score]\n",
        "final_evaluation": "[Final Evaluation]\n",
        "achievement_rate_label": "Substat Achievement",
        "achievement_rate_desc": "Percentage relative to theoretical max of top 5 weighted substats",
        "sss_desc": "SSS - Perfect set! Theoretical maximum performance.",
        "ss_desc": "SS - Excellent set. Almost complete.",
        "s_desc": "S - Great set. Sufficient for combat.",
        "a_desc": "A - Good set. No issues using it.",
        "b_desc": "B - Acceptable. Room for improvement.",
        "c_desc": "C - Needs improvement. Keep farming.",
        "normalized_score_desc": "Normalized by max value and weighted",
        "ratio_score_desc": "Considers substat ratio and damage increase",
        "roll_quality_desc": "Evaluates roll quality of each substat",
        "effective_stat_desc": "Bonus for number of effective substats",
        "normalized_score_label": "Normalized Score",
        "ratio_score_label": "Ratio Score",
        "roll_quality_label": "Roll Quality",
        "effective_stat_label": "Effective Stat Count",
        "cost_label": "Cost: {}",
        "score_point": "{:.2f} pts",
        "score_per_item": "{:.2f} pts/item",
        "score_point_count": "{:.2f} pts [{} items]",
        "total_score_label": "Total Score",
        "total_label": "Total",
        "normalized_label": "Norm",
        "ratio_label": "Ratio",
        "roll_label": "Roll",
        "effective_label": "Eff",
        "effective_count_label": "Eff#",
        "recommend_label": "Rec",
        "warning": "Warning",
        "no_data": "No calculable echo data",
        "individual_eval_done": "Individual eval done: {} - Total {:.2f} pts",
        "batch_eval_done": "Batch eval done: {} items calculated",
        "calc_error": "Calc Error:\n{}",
        "batch_calc_error": "Batch calc error: {}",
        "batch_error_msg": "Error in batch calculation:\n{}",
        "image_load_error": "Failed to load image:\n{}",
        "image_load_error_log": "Image load error: {}",
        "pytesseract_not_installed": "pytesseract not installed, cannot perform OCR",
        "tesseract_found_path": "Tesseract found in PATH: {}",
        "tesseract_not_found_sys": "Tesseract not found. Please configure path or install on system.",
        "ocr_error_title": "OCR Error",
        "ocr_lang_data_error_log": "OCR lang data error: {}",
        "tesseract_exec_not_found": "Tesseract executable not found:\n{}",
        "tesseract_exec_error_log": "Tesseract exec error: {}",
        "ocr_process_error_log": "OCR process error: {}",
        "crop_title": "Crop Image",
        "crop_instruction": "Drag mouse to select crop area.",
        "crop_sync_notice": "* The saved position (L,T) and size (W,H) will sync with the main UI sliders and be used for Auto Calculation.",
        "crop_confirm_apply": "Confirm Apply",
        "crop_apply_percent": "Apply as Percentage Area",
        "crop_apply_percent_tooltip": "Treat the width/height of the selected area as a percentage and crop relative to the original image. E.g., 50% x 50%",
        "crop_save_as_default": "Save as Default",
        "crop_save_as_default_tooltip": "Save the current selection (or preset value) as the default for future sessions. Persists after app restart.",
        "crop_confirm_needed": "Please check the box to confirm apply",
        "preset_name_placeholder": "Name",
        "preset_placeholder_format": "L,T,W,H (%)",
        "preset_name_required": "Please enter a preset name",
        "preset_format": "Invalid preset format (e.g., 50x50)",
        "ok": "OK",
        "cancel": "Cancel",
        "reset": "Reset",
        "save": "Save",
        "load": "Load",
        "delete": "Delete",
        "info": "Info",
        "crop_too_small": "Selection area is too small",
        "text_color": "Text Color:",
        "select_color": "Select Color",
        "apply": "Apply",
        "background_image": "Background Image:",
        "select_image": "Select Image",
        "clear_image": "Clear",
        "bg_opacity": "Background Opacity:",
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "ATK",
        "攻撃力%": "ATK%",
        "防御力": "DEF",
        "防御力%": "DEF%",
        "クリティカル率": "Crit Rate",
        "クリティカルダメージ": "Crit DMG",
        "共鳴効率": "Energy Regen",
        "通常攻撃ダメージアップ": "Basic ATK DMG Bonus",
        "重撃ダメージアップ": "Heavy ATK DMG Bonus",
        "共鳴スキルダメージアップ": "Skill DMG Bonus",
        "共鳴解放ダメージアップ": "Liberation DMG Bonus",
        "焦熱ダメージアップ": "Fusion DMG Bonus",
        "凝縮ダメージアップ": "Glacio DMG Bonus",
        "電導ダメージアップ": "Electro DMG Bonus",
        "気動ダメージアップ": "Aero DMG Bonus",
        "回折ダメージアップ": "Spectro DMG Bonus",
        "消滅ダメージアップ": "Havoc DMG Bonus",
        "HP回復効果アップ": "Healing Bonus",
        # Ratings
        "rating_sss_norm": "SS - Top Quality",
        "rating_ss_norm": "S - Excellent",
        "rating_s_norm": "A - Practical",
        "rating_b_norm": "B - Needs Improvement",
        "rating_perf_ratio": "Perfect - Near Theoretical Max",
        "rating_exc_ratio": "Excellent - Very Strong",
        "rating_good_ratio": "Good - Usable",
        "rating_avg_ratio": "Average - Recommended to Improve",
        "rating_weak_ratio": "Weak - Needs Farming",
        "rating_god_roll": "God Roll - Max Rolls Streak",
        "rating_win_roll": "Win - Many High Rolls",
        "rating_avg_roll": "Average - Standard Rolls",
        "rating_bad_roll": "Loss - Low Quality Rolls",
        "rating_perf_eff": "Perfect - 5 Effective Stats ({:.1f} pts)",
        "rating_exc_eff": "Excellent - 4 Effective Stats ({:.1f} pts)",
        "rating_good_eff": "Good - 3 Effective Stats ({:.1f} pts)",
        "rating_bad_eff": "Improve - {} Effective Stats ({:.1f} pts)",
        "rating_sss_global": "SSS - Perfect Echo Set!",
        "rating_ss_global": "SS - Very Excellent",
        "rating_s_global": "S - Excellent",
        "rating_a_global": "A - Good",
        "rating_b_global": "B - Passing Grade",
        "rating_c_global": "C - Needs Improvement",
        "rec_continue": "Continue Farming",
        "rec_use": "Recommended to Use",
        "theme": "light/dark",
        "display_settings": "Display Settings",
        "rating_sss_single": "SSS - Perfect Echo!",
        "rating_ss_single": "SS - High Quality Echo",
        "rating_s_single": "S - Good Echo",
        "rating_a_single": "A - Decent Echo",
        "rating_b_single": "B - Usable",
        "rating_c_single": "C - Needs Improvement",
        # CV Method Ratings
        "rating_outstanding_cv": "Outstanding - 45+ pts (SSS tier)",
        "rating_excellent_cv": "Excellent - 38~45 pts (S tier)",
        "rating_good_cv": "Good - 30~38 pts (Target Achieved)",
        "rating_acceptable_cv": "Acceptable - 25~30 pts (Passing Grade)",
        "rating_weak_cv": "Weak - Below 25 pts",
        # Method Labels
        "cv_score_label": "CV (Crit Value) Method - Community Standard",
        "cv_score_desc": "Crit-value based evaluation (30pt pass / 38pt target)",
        # Method Selection
        "calc_methods": "Calculation Methods:",
        "method_normalized": "Normalized",
        "method_ratio": "Ratio-Based",
        "method_roll": "Roll Quality",
        "method_effective": "Effective Stats",
        "method_cv": "CV (Crit Value)",
        "no_methods_selected": "Please select at least one calculation method",
        "dark_theme": "Dark",
        "light_theme": "Light",
        "clear_theme": "Clear",
        "input_bg_color": "Input Background Color",
        "reset": "Reset",
        "full_reset": "Reset All Display Settings",
        "confirm_full_reset": "Are you sure you want to reset all display settings?",
        "help_customization": "Customization Guide",
        "font_settings": "Font Settings",
        "font_family": "Font Family:",
        "default_font": "System Default",
        "weight_template": "Weight Template:",
        "custom": "Custom",
        "title_warning": "Warning",
        "warn_legacy_bg_not_found": "The previously set background image could not be found at:\n\n{0}\n\nThe setting has been cleared.",
        "cleanup_title": "Cleanup Background Images",
        "cleanup_button": "Cleanup",
        "cleanup_no_folder": "The 'images' folder was not found.",
        "cleanup_no_unused": "There are no unused background images.",
        "cleanup_confirm": "Are you sure you want to delete {} unused images?\n\n{}",
        "cleanup_error": "Deleted {} images, but an error occurred while deleting the following files:\n\n{}",
        "cleanup_success": "Successfully deleted {} unused images.",
        "cleanup_unexpected_error": "An unexpected error occurred during cleanup:\n{}",
        "new": "New",
        "edit": "Edit",
        "char_setting_new": "Character Settings (New)",
        "char_setting_edit": "Character Settings (Edit)",
        "history_title": "Calculation History",
        "history": "History",
        "preprocess_settings": "Preprocessing",
        "history_search": "Search:",
        "history_char": "Char:",
        "history_cost": "Cost:",
        "history_rating": "Rating:",
        "history_from": "From:",
        "history_to": "To:",
        "history_filter_date": "Filter by Date",
        "history_reset": "Reset",
        "history_clear": "Clear All History",
        "history_stats": "Count: {} | Average: {:.2f} | Max: {:.2f}",
        "history_no_data": "No score data available for current filters.",
        "history_col_time": "Timestamp",
        "history_col_char": "Character",
        "history_col_cost": "Cost",
        "history_col_action": "Action",
        "history_col_result": "Result",
        "history_duplicate_mode": "Duplicate History Behavior:",
        "history_dup_all": "Keep All (Allow Duplicates)",
        "history_dup_latest": "Keep Latest (Remove Old)",
        "history_dup_oldest": "Keep Oldest (Ignore New)",
        "history_duplicate_tooltip": "Sets behavior when an echo with the same stats is calculated.\n- Keep All: Add every time without checking.\n- Keep Latest: Delete old entry and replace with the current result.\n- Keep Oldest: Do nothing if already exists, preserving the original timestamp.",
    }
}
